# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)



platform :ios do

  desc "Create App On appstoreconnect"
  lane :create_app do
    create_app_online(
      username: 'manoj.mirchandani@gmail.com',
      app_identifier: 'com.hiteshi.CustomExpandingView',
      app_name: 'CustomExpandingView',
      language: 'English',
      app_version: '1.0',
      sku: '123',
      team_name: 'Manoj Mirchandani'
    )
  end

  desc "Sync singing Certificate"
  lane :signing do
    sync_code_signing(
    type: "appstore",  # match
    app_identifier: "com.hiteshi.CustomExpandingView",
    username:'manoj.mirchandani@gmail.com',
    team_id:'T4Q3XEB88Y',
    team_name:'Manoj Mirchandani',
    git_url:'https://github.com/harshHiteshi/CustomExpandingView.git'
    )
    mapping = lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
     update_code_signing_settings(
      profile_name: mapping['com.hiteshi.CustomExpandingView'],
      use_automatic_signing: false,
      path: "/Users/neeleshwarimehra/Downloads/GitProject/CustomExpandingView1/CustomExpandingView/CustomExpandingView.xcodeproj",
      team_id: "T4Q3XEB88Y",
      bundle_identifier: "com.hiteshi.CustomExpandingView",
      code_sign_identity:"Apple Distribution",
      build_configurations:"Release"
     )
   end

    desc "Build binary"
    lane :build do
     build_ios_app #gym
   end 

   desc "Release app to appstore"
   lane :release do
    build
    # deliver
    upload_to_app_store(
    app_identifier:'com.hiteshi.CustomExpandingView',
    team_name:'Manoj Mirchandani',
    dev_portal_team_name:'Manoj Mirchandani',
    run_precheck_before_submit:false,
    skip_screenshots:true,
    skip_metadata:true
   ) 
   end
end

